In [ ]:
import pandas as pd
import numpy as np



Напишіть функцію гіпотези лінійної регресії у векторному вигляді;

In [ ]:
df = pd.read_csv("/content/Housing.csv")


In [ ]:
X = df[["area", "bedrooms","bathrooms"]]
y = df["price"]
X = (X - X.mean(axis=0)) / X.std(axis=0)
X_with_intercept = np.hstack((np.ones((X.shape[0], 1)), X))
print(X_with_intercept)
w = np.zeros(X_with_intercept.shape[1])
print(w.shape)
learning_rate = 0.01
n_epochs = 1000


[[ 1.          1.04576555  1.40213123  1.42050672]
 [ 1.          1.75539685  1.40213123  5.4008469 ]
 [ 1.          2.2161964   0.04723492  1.42050672]
 ...
 [ 1.         -0.70527273 -1.30766139 -0.56966336]
 [ 1.         -1.03244041  0.04723492 -0.56966336]
 [ 1.         -0.59928883  0.04723492 -0.56966336]]
(4,)


In [ ]:
def hypothesis(w, X):
  return np.dot(X, w)

In [ ]:
hyp = hypothesis(w, X_with_intercept)


Створіть функцію для обчислення функції втрат у векторному вигляді;

In [ ]:
def loss_fuction(w, X, y):
    m = len(y)
    h = hypothesis(w, X)
    cost = (1/(2*m)) * np.sum((h - y)**2)
    return cost

In [ ]:
loss = loss_fuction(w, X_with_intercept, y)
print(loss)

13106916364659.268


Реалізуйте один крок градієнтного спуску;

In [ ]:
def gradient_descent_step(w, X, y, learning_rate):
    m = len(y)
    h = hypothesis(w, X)

    gradient = (1 / m) * X.T @ (h - y)

    w -= learning_rate * gradient
    return w


In [ ]:
step = gradient_descent_step(w, X_with_intercept, y, learning_rate)
print(step)

[47667.29247706 10007.11126918  6842.47137471  9662.61090575]


Знайдіть найкращі параметри $\vec{w}$ для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [ ]:
def gradient_descent(X, y, weight, learning_rate, n_epochs):


    for epoch in range(n_epochs):
        loss = loss_fuction(weight, X, y)
        w = gradient_descent_step(weight, X, y, learning_rate)
        print(f'Epoch {epoch + 1}, Loss: {loss}')
        print(f'Optimal weights using Gradient Descent: {w}')
    return w

In [ ]:
optimal_w = gradient_descent(X_with_intercept, y, w, learning_rate, n_epochs)



Epoch 1, Loss: 895585104082.9313
Optimal weights using Gradient Descent: [4766527.55719312  821953.73579121  300571.85273916  696155.24295148]
Epoch 2, Loss: 895585102937.1445
Optimal weights using Gradient Descent: [4766529.57409825  821953.97599513  300569.84590989  696157.02439102]
Epoch 3, Loss: 895585101808.8269
Optimal weights using Gradient Descent: [4766531.57083433  821954.21339693  300567.85209887  696158.79507452]
Epoch 4, Loss: 895585100697.6975
Optimal weights using Gradient Descent: [4766533.54760305  821954.44802565  300565.87122055  696160.55506618]
Epoch 5, Loss: 895585099603.4799
Optimal weights using Gradient Descent: [4766535.50460409  821954.67991006  300563.90318995  696162.3044298 ]
Epoch 6, Loss: 895585098525.902
Optimal weights using Gradient Descent: [4766537.44203511  821954.90907862  300561.94792266  696164.04322883]
Epoch 7, Loss: 895585097464.6973
Optimal weights using Gradient Descent: [4766539.36009182  821955.13555955  300560.00533483  696165.77152633]


Знайдіть ці ж параметри за допомогою аналітичного рішення;

In [ ]:
def analytical_solution(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

In [ ]:
analytical_solution = analytical_solution(X_with_intercept, y)
analytical_solution

array([4766729.24770642,  821968.58935343,  300259.16468032,
        696447.75898578])

Порівняйте отримані результати.

In [ ]:
print(optimal_w)
print(analytical_solution)

[4766525.51991521  821953.49275582  300573.87267281  696153.45069131]
[4766729.24770642  821968.58935343  300259.16468032  696447.75898578]
